"""Generate ANIM B's detailed map. Run with Python, GeoPandas and Shapely installed.

Natural Earth 1:10m Admin 0 Countries 5.1.1 is public domain. The source archive is
cached outside the shipped site and checked so future upstream changes are explicit.
Only the two Koreas' exterior rings are emitted; no geospatial runtime is shipped.
"""

from hashlib import sha256
from math import log, pi, tan
from pathlib import Path
from urllib.request import urlretrieve

import geopandas as gpd
from shapely.ops import transform

ROOT = Path(__file__).resolve().parents[1]
SOURCE = "https://naturalearth.s3.amazonaws.com/10m_cultural/ne_10m_admin_0_countries.zip"
SOURCE_SHA256 = "ce1ac7036499a0edd641fbc093cd209a98f96a49d2eca8480aaacad35138a7f6"
ARCHIVE = ROOT / ".design-sync/.cache/maps/ne_10m_admin_0_countries.zip"
OUTPUT = ROOT / "design-system/src/sections/koreaCoastline.ts"


def project(lon, lat, z=None):
    # Mercator calibrated against the original 18 mainland vertices. The fit's
    # maximum residual is 0.032 map units (<0.08px on desktop), preserving the
    # the shared coordinates used by generate-korea-coverage.py.
    return (
        17.946886061743193 * lon - 2213.627427532487,
        -1028.132034673909 * log(tan(pi / 4 + lat * pi / 360)) + 861.8836301237753,
    )


def ring_path(polygon):
    points = list(polygon.exterior.coords)[:-1]
    # Start the tracing effect at the northern tip rather than an arbitrary GIS vertex.
    first = min(range(len(points)), key=lambda i: (points[i][1], points[i][0]))
    points = points[first:] + points[:first]
    return "M" + "L".join(f"{x:.3f},{y:.3f}" for x, y in points) + "Z"


ARCHIVE.parent.mkdir(parents=True, exist_ok=True)
if not ARCHIVE.exists():
    urlretrieve(SOURCE, ARCHIVE)
if sha256(ARCHIVE.read_bytes()).hexdigest() != SOURCE_SHA256:
    raise ValueError("Natural Earth archive changed; review the new source before regenerating.")

countries = gpd.read_file(ARCHIVE)
output = [
    "/**",
    " * Generated by .design-sync/generate-korea-map.py; edit the generator, not these paths.",
    " * Natural Earth 1:10m Admin 0 Countries 5.1.1 (public domain).",
    " * Source: https://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-0-countries/",
    f" * Archive SHA-256: {SOURCE_SHA256}",
    " * Coordinates retain ANIM B's shared map projection and coverage alignment.",
    " * Mainland simplification: 0.14 map units (~0.3px desktop); islands: 0.10 units.",
    " */",
    "",
]

for code, name in [("PRK", "PENINSULA"), ("KOR", "ROK")]:
    geometry = countries.loc[countries.ADM0_A3 == code].geometry.iloc[0]
    projected = transform(project, geometry)
    polygons = sorted(projected.geoms, key=lambda p: p.area, reverse=True)
    mainland = polygons[0].simplify(0.14, preserve_topology=True)
    # Keep every source island, including Jeju, Ulleungdo and the small eastern islands.
    islands = [p.simplify(0.10, preserve_topology=True) for p in polygons[1:]]
    if not mainland.is_valid or not all(p.is_valid for p in islands):
        raise ValueError(f"Invalid simplified geometry for {code}")
    for label, rings in [(f"{name}_PATH", [mainland]), (f"{name}_ISLANDS_PATH", islands)]:
        output.append(f"export const {label} =")
        for i, polygon in enumerate(rings):
            output.append(f"  '{ring_path(polygon)}'" + (";" if i == len(rings) - 1 else " +"))
        output.append("")
    print(f"{code}: {len(mainland.exterior.coords) - 1} mainland vertices, {len(islands)} islands")

OUTPUT.write_text("\n".join(output), encoding="utf-8")
print(f"Generated {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size:,} bytes)")
