"""Generate six 100km geodesic footprints and verify complete mainland coverage.

Run after generate-korea-map.py with GeoPandas, Shapely and pyproj installed.
Stations were found by a geographic set-cover search, then adjusted to close the
small interior gap between neighboring disks. Islands are outside the requested
coverage scope; their coastline remains visible on the map.
"""

from hashlib import sha256
from math import log, pi, tan
from pathlib import Path

import geopandas as gpd
from pyproj import Geod
from shapely.geometry import Polygon
from shapely.ops import transform, unary_union

ROOT = Path(__file__).resolve().parents[1]
ARCHIVE = ROOT / ".design-sync/.cache/maps/ne_10m_admin_0_countries.zip"
SOURCE_SHA256 = "ce1ac7036499a0edd641fbc093cd209a98f96a49d2eca8480aaacad35138a7f6"
RADIUS_KM = 100
# The first station receives the aircraft animated out of scene 1.
STATIONS = [
    ("northwest", 127.3884, 38.1116),
    ("northeast", 128.4807, 37.7879),
    ("central-west", 126.9967, 36.7034),
    ("central-east", 128.9400, 36.3790),
    ("southwest", 127.0170, 35.0813),
    ("southeast", 128.4669, 35.5171),
]


def project(lon, lat, z=None):
    # Same calibrated Mercator transform as generate-korea-map.py.
    return (
        17.946886061743193 * lon - 2213.627427532487,
        -1028.132034673909 * log(tan(pi / 4 + lat * pi / 360)) + 861.8836301237753,
    )


if sha256(ARCHIVE.read_bytes()).hexdigest() != SOURCE_SHA256:
    raise ValueError("Unexpected coastline source; regenerate/review the map first.")
source = gpd.read_file(ARCHIVE)
country = source.loc[source.ADM0_A3 == "KOR"].geometry.iloc[0]
mainland = max(country.geoms, key=lambda polygon: polygon.area)
projected_mainland = transform(project, mainland)
geod = Geod(ellps="WGS84")
footprints = []
rows = []

for station_id, lon, lat in STATIONS:
    geographic_ring = [geod.fwd(lon, lat, bearing, RADIUS_KM * 1000)[:2] for bearing in range(360)]
    # Validate the exact rounded polygon shipped to the browser, not just an ideal circle.
    points = [tuple(round(v, 3) for v in project(*point)) for point in geographic_ring]
    polygon = Polygon(points)
    if not polygon.is_valid:
        raise ValueError(f"Invalid footprint for {station_id}")
    footprints.append(polygon)
    cx, cy = project(lon, lat)
    west = project(*geod.fwd(lon, lat, 270, RADIUS_KM * 1000)[:2])
    d = "M" + "L".join(f"{x:.3f},{y:.3f}" for x, y in points) + "Z"
    rows.append(
        "  {\n"
        f"    id: '{station_id}', lon: {lon:.4f}, lat: {lat:.4f},\n"
        f"    cx: {cx:.3f}, cy: {cy:.3f}, westX: {west[0]:.3f}, westY: {west[1]:.3f},\n"
        f"    d: '{d}',\n"
        "  },"
    )

coverage = unary_union(footprints)
for label, geometry in [
    ("Natural Earth mainland", projected_mainland),
    ("displayed mainland", projected_mainland.simplify(0.14, preserve_topology=True)),
]:
    uncovered = geometry.difference(coverage)
    if not uncovered.is_empty:
        raise ValueError(f"{label} has an uncovered area: {uncovered.area:.8f} map units squared")
    print(f"{label}: fully inside the six 100km footprints")

header = """/**
 * Generated by .design-sync/generate-korea-coverage.py.
 * Six WGS84 geodesic disks, each with a 100km ground radius.
 * Their union covers the complete Natural Earth 1:10m ROK mainland and the displayed outline.
 * Islands are not included in the coverage requirement. This is a geometric coverage illustration.
 * The animation selects its arrival station by id and omits the duplicate stationary mark there.
 */

export { PENINSULA_PATH, PENINSULA_ISLANDS_PATH, ROK_PATH, ROK_ISLANDS_PATH } from './koreaCoastline';

export const COVERAGE_RADIUS_KM = 100;

export const COVERAGE: Array<{
  id: string;
  lon: number;
  lat: number;
  cx: number;
  cy: number;
  westX: number;
  westY: number;
  d: string;
}> = [
"""
destination = ROOT / "design-system/src/sections/koreaCoverage.ts"
destination.write_text(header + "\n".join(rows) + "\n];\n", encoding="utf-8")
print(f"Generated {destination.relative_to(ROOT)}: {len(rows)} stations, {RADIUS_KM}km radius")
