// Builds the ICARUS design-system package:
//   1. optimizes the site's images (../static) into generated/assets/*.webp
//   2. bundles src/index.ts -> dist/index.js (ESM, react external, images inlined as data URLs)
//   3. emits .d.ts declarations -> dist/
//   4. compiles Tailwind CSS v4 -> dist/styles.css
import { build } from 'esbuild';
import sharp from 'sharp';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const staticDir = resolve(root, '..', 'static');
const assetsDir = join(root, 'generated', 'assets');
const dist = join(root, 'dist');

rmSync(dist, { recursive: true, force: true });
mkdirSync(assetsDir, { recursive: true });
const thisScript = fileURLToPath(import.meta.url);

// The live site's images are far larger than a bundle can carry (about_img.gif alone
// is 21 MB), so each is resized to at most ~2x its on-page display size.
// .ico files are PNG-in-ICO: read the embedded PNG from the first directory entry.
function icoPng(file) {
  const buf = readFileSync(file);
  const size = buf.readUInt32LE(6 + 8);
  const offset = buf.readUInt32LE(6 + 12);
  return buf.subarray(offset, offset + size);
}

// The homepage photograph is whichever file static/hero/SELECTED.txt names (see static/hero/CREDITS.md).
const heroDir = join(staticDir, 'hero');
const selectedHero =
  (existsSync(join(heroDir, 'SELECTED.txt')) ? readFileSync(join(heroDir, 'SELECTED.txt'), 'utf8').trim() : '') ||
  '01-excite-balloon-stratosphere';
const heroPath = join(heroDir, `${selectedHero}.jpg`);
if (!existsSync(heroPath)) {
  throw new Error(`static/hero/SELECTED.txt names "${selectedHero}" but ${heroPath} does not exist`);
}
const heroCredits = JSON.parse(readFileSync(join(heroDir, 'credits.json'), 'utf8'));
const heroInfo = heroCredits[selectedHero] ?? { credit: 'NASA', caption: '' };
console.error(`  hero photo: ${selectedHero} (${heroInfo.credit})`);

const images = [
  // NASA imagery, public domain; the credit travels with it into the footer.
  { srcPath: heroPath, out: 'hero-stratosphere.webp', resize: { width: 1920 }, webp: { quality: 72 } },
  { src: 'bg_rec.png', out: 'logo.webp', resize: { height: 96 }, webp: { quality: 90, alphaQuality: 100 } },
  { src: 'bg-white_circle.ico', out: 'logo-circle.webp', ico: true, resize: { width: 96, height: 96 }, webp: { quality: 90, alphaQuality: 100 } },
  { src: 'airship_3d.png', out: 'airship-3d.webp', resize: { width: 1024 }, webp: { quality: 82, alphaQuality: 90 } },
  { src: 'about_img.gif', out: 'about.webp', animated: true, resize: { width: 448 }, webp: { quality: 55, effort: 6 } },
  { src: 'product_img.png', out: 'product.webp', resize: { width: 896 }, webp: { quality: 78 } },
  { src: 'news_img_4.png', out: 'news-material.webp', resize: { width: 800 }, webp: { quality: 78 } },
  { src: 'news_img_3.jpg', out: 'news-award.webp', resize: { width: 800 }, webp: { quality: 78 } },
  { src: 'news_img_1.png', out: 'news-ytn.webp', resize: { width: 800 }, webp: { quality: 78 } },
  { src: 'news_img_2.jpg', out: 'news-kepco.webp', resize: { width: 800 }, webp: { quality: 78 } },
];

for (const img of images) {
  // Skip images already converted from the current source with the current settings.
  const srcPath = img.srcPath ?? join(staticDir, img.src);
  const outPath = join(assetsDir, img.out);
  if (existsSync(outPath) && statSync(outPath).mtimeMs > Math.max(statSync(srcPath).mtimeMs, statSync(thisScript).mtimeMs)) {
    continue;
  }
  const input = img.ico ? icoPng(srcPath) : srcPath;
  const info = await sharp(input, { animated: !!img.animated })
    .resize({ ...img.resize, withoutEnlargement: true })
    .webp(img.webp)
    .toFile(outPath);
  console.error(`  image ${img.src ?? selectedHero} -> ${img.out} (${info.width}x${info.height}, ${(info.size / 1024).toFixed(0)} KB)`);
}

// The footer credit follows the selected photograph.
mkdirSync(join(root, 'src', 'generated'), { recursive: true });
writeFileSync(
  join(root, 'src', 'generated', 'hero.ts'),
  `// Generated by scripts/build.mjs from static/hero/SELECTED.txt - do not edit.\n` +
    `/** Credit line for the hero photograph currently in the bundle. */\n` +
    `export const heroCredit = ${JSON.stringify(`Hero photograph: ${heroInfo.credit}, public domain.`)};\n` +
    `/** File name (in static/hero/) of the photograph currently in the bundle. */\n` +
    `export const heroPhotoName = ${JSON.stringify(selectedHero)};\n` +
    `/** Where this photograph should be anchored when cropped to the hero band. */\n` +
    `export const heroPosition: 'top' | 'center' | 'bottom' = ${JSON.stringify(heroInfo.position ?? 'center')};\n`,
);

await build({
  entryPoints: [join(root, 'src', 'index.ts')],
  outfile: join(dist, 'index.js'),
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2020',
  jsx: 'automatic',
  external: ['react', 'react/jsx-runtime', 'react-dom'],
  loader: { '.webp': 'dataurl' },
  legalComments: 'none',
});
console.error('  js   -> dist/index.js');

const bin = (name) => join(root, 'node_modules', '.bin', name);
execFileSync(bin('tsc'), ['-p', join(root, 'tsconfig.json')], { stdio: 'inherit' });
console.error('  d.ts -> dist/');

execFileSync(bin('tailwindcss'), ['-i', join(root, 'src', 'styles.css'), '-o', join(dist, 'styles.css')], {
  stdio: 'inherit',
  cwd: root,
});
console.error('  css  -> dist/styles.css');
